$.fn.rotate=function(a){this.css({"-ms-transform":"rotate("+a+"deg)","-webkit-transform":"rotate("+a+"deg)","-moz-transform":"rotate("+a+"deg)","-o-transform":"rotate("+a+"deg)",transform:"rotate("+a+"deg)"})};
function BackIssues(a,b,d){this.issuesBottom=40;this.issuesTop=60;this.issuesRight=0;this.issuesHeight=b.height()-this.issuesTop-this.issuesBottom;this.issuesWidth=152;this.father=b;this.outIssues=$("<div>",{css:{position:"absolute",width:this.issuesWidth,height:this.issuesHeight,left:"auto",right:-this.issuesWidth,top:this.issuesTop,backgroundColor:"#efefef",borderTopLeftRadius:4,borderBottomLeftRadius:4}}).appendTo(b);this.issuesShow=!1;this.showHide=$("<div>",{css:{position:"absolute",left:-28,
top:64,cursor:"pointer"}}).append($("<img>",{src:d+"backissues.png"})).appendTo(this.outIssues);this.lBoxShow=$("<div>",{css:{position:"absolute",width:this.issuesWidth,borderRadius:4,boxShadow:"0px 0px 4px rgba(0,0,0,0.5)",height:this.issuesHeight-1,backgroundColor:"transparent",left:0,top:1}}).appendTo(this.outIssues);this.bBoxShow=$("<div>",{css:{position:"absolute",width:"100%",height:this.issuesHeight-2,left:1,backgroundColor:"transparent",top:"auto",borderRadius:4,boxShadow:"0px 0px 4px rgba(0,0,0,0.5)",
bottom:0}}).appendTo(this.outIssues);this.issues=$("<div>",{"class":"BackIssues",css:{position:"absolute",width:this.issuesWidth,height:"100%",backgroundColor:"#efefef",borderTopLeftRadius:4,borderBottomLeftRadius:4}}).appendTo(this.outIssues);this.createTitle(a,this.issues,d);this.bindEvents();var c=this;$(window).on("resize",function(){c.resize(b);c.calculateScrollBar()});return this}
BackIssues.prototype={show:function(){this.issuesShow=!0;this.outIssues.stop(!1,!1).animate({right:this.issuesRight},{duration:300,easing:"linear"})},hide:function(){this.issuesShow=!1;this.outIssues.stop(!1,!1).animate({right:-this.issuesWidth},{duration:300,easing:"linear"});return this},setHide:function(){this.issuesShow=!1;this.outIssues.css({right:-this.issuesWidth});return this},createTitle:function(a,b,d){this.titleTop=20;this.titleLeft=10;this.titleWidth=this.issuesWidth-2*this.titleLeft;
this.titleHeight=28;this.title=$("<div>",{"class":"backIssuesTitle",css:{position:"absolute",width:this.titleWidth,height:this.titleHeight,left:this.titleLeft,top:this.titleTop}}).appendTo(b);this.innerTitle=$("<div>",{"class":"innerTitle",position:"absolute",width:"100%",height:"100%",left:0,top:0,cursor:"pointer"}).appendTo(this.title);this.titleText=$("<div>",{"class":"TitleText textEllipsis",css:{position:"absolute",width:this.titleWidth-2-18,height:this.titleHeight,left:0,top:0,fontFamily:"Helvetica, Arial, sans-serif, Cambria",
fontSize:14,lineHeight:this.titleHeight+"px",verticalAlign:"middle",textIndent:5,overflow:"hidden"}}).appendTo(this.innerTitle);this.createTitleList(a,this.title,d)},createTitleList:function(a,b,d){var c=this;this.titleListTop=this.titleHeight;this.titleListWidth=this.titleWidth-2;this.titleList=$("<ul>",{"class":"dropdown",css:{position:"absolute",top:this.titleListTop,width:this.titleListWidth,height:"auto",listStyle:"none",zIndex:1,margin:0,padding:0}}).appendTo(b);this.createBook(a,this.issues);
this.createBooks(this.booksList,a[0].books,d);for(b=0;b<a.length;b++)0===b&&this.titleText.html(a[0].title).attr("data-id",a[0].id),this.titleOption=$("<li>",{"class":"textEllipsis",css:{fontFamily:"Helvetica, Arial, sans-serif, Cambria",fontSize:14,padding:"6px 0px 6px 0px",textIndent:5}}).html(a[b].title).attr("data-id",a[b].id).appendTo(this.titleList),b==a.length-1&&this.titleOption.css({borderBottom:"none"}),this.titleOption.bind("click",function(){if($(this).attr("data-id")!=c.titleText.attr("data-id")){c.titleText.html($(this).html()).attr("data-id",
$(this).attr("data-id"));for(var b=0;b<a.length;b++)a[b].id==$(this).attr("data-id")&&c.createBooks(c.booksList,a[b].books,d)}})},createBook:function(a,b){this.bookBottom=17;this.bookViewLeft=16;this.bookViewTop=this.titleHeight+this.titleTop+this.bookBottom;this.bookViewWidth=this.issuesWidth-this.bookViewLeft;this.bookViewHeight=this.issuesHeight-this.bookViewTop-this.bookBottom;this.bookListWidth=this.issuesWidth-2*this.bookViewLeft;this.outBookView=$("<div>",{css:{position:"absolute",width:this.issuesWidth,
height:this.bookViewHeight,left:0,top:this.bookViewTop}}).appendTo(b);this.bookView=$("<div>",{"class":"BookView",css:{position:"absolute",width:this.bookViewWidth,height:"100%",left:this.bookViewLeft,top:0,overflow:"hidden"}}).appendTo(this.outBookView);this.booksList=$("<div>",{"class":"BookList",css:{position:"relative",width:this.bookListWidth,height:"auto",paddingTop:6,paddingBottom:6,left:0,top:0}}).appendTo(this.bookView);this.description=$("<span>",{"class":"Description",css:{position:"absolute",
display:"block",width:240,borderRadius:4,border:"1px solid #ffffff",right:this.issuesWidth+8,padding:11,zIndex:250,backgroundColor:"#ffffff",boxShadow:"inset 0px 0px 7px rgba(0, 0, 0, 0.42)"}}).appendTo(this.outBookView).hide();this.bookName=$("<span>",{css:{position:"relative",display:"block",fontSize:14,color:"#000000",fontWeight:"bold",wordWrap:"break-word",fontFamily:"Helvetica, Arial, sans-serif, Cambria",lineHeight:"17px"}}).appendTo(this.description);this.bookDes=$("<span>",{css:{position:"relative",
display:"block",fontSize:11,color:"#000000",fontFamily:"Helvetica, Arial, sans-serif, Cambria",lineHeight:"17px"}}).appendTo(this.description);this.point=$("<div>",{css:{position:"absolute",display:"block",border:"8px solid transparent",borderLeftColor:"#ffffff",top:"50%",left:-8}}).appendTo(this.outBookView).hide()},createBooks:function(a,b,d){var c=this,e=this.bookListWidth-16,f=e-8;this.scrollBar&&(this.scrollBar.remove(),this.bookView.unbind($.browser.mozilla?"DOMMouseScroll":"mousewheel"));a.empty();
a.css({top:0});for(var g=0;g<b.length;g++){var h=$("<a>",{target:"_blank",href:b[g].url,css:{position:"relative",width:e,height:"auto",left:8,display:"block",opacity:0.5,textDecoration:"none"}}).appendTo(a),i=$("<div>",{css:{position:"relative",left:0,top:0,width:e,height:"100%"}}).appendTo(h);$("<div>",{css:{position:"relative",width:"100%",height:"auto",left:0,top:0}}).append($("<div>",{"class":"BottomPicture",id:"BottomPicture"+g,css:{position:"absolute",width:30,border:"1px solid #c6c6c6",height:30,
left:(f-24)/2,boxShadow:"0px 0px 1px #000000",backgroundColor:"#ffffff",transform:"rotate(3deg)"}})).append($("<img>",{id:"BookImage"+g,src:d+"loading.gif",css:{position:"relative",display:"block",width:24,height:24,border:"4px solid #ffffff",boxShadow:"0px 0px 1px #000000",left:(f-24)/2}})).appendTo(i);$(".BottomPicture").rotate(3);(function(a){var d=new Image;d.onload=function(){d.onload=null;var e=Math.round(f/(this.width/this.height));$("#BookImage"+a)[0].src=b[a].src;$("#BookImage"+a).animate({left:0,
width:f,height:e},{duration:400,step:function(a,b){if(b.prop=="height"){c.calculateScrollBar();c.setDescriptionPosition2()}},complete:function(){c.calculateScrollBar()}});$("#BottomPicture"+a).animate({width:f+8-2,height:e+8-2,left:0},{duration:400});var g=Math.asin(4/((e+8)/2))/Math.PI*180,e=Math.sin(3/180*Math.PI)*((e+8)/2);g<3&&e>4&&$("#BottomPicture"+a).rotate(g)};d.onerror=function(){$("#BookImage"+a).css({left:(f-18)/2});$("#BottomPicture"+a).css({width:26,height:28,left:(f-18)/2});$("#BookImage"+
a)[0].src=b[a].src;c.calculateScrollBar();setTimeout(function(){c.calculateScrollBar()},500)};d.src=b[a].src;h.bind("mousemove",function(){});h.bind("mouseout",function(){c.point.hide();c.description.hide();$(this).stop(false,true).animate({opacity:0.5},500)});h.bind("mouseleave",function(){c.point.hide();c.description.hide()});h.bind("mouseenter",function(){c.overObj=$(this);c.setDescriptionPosition(b,a,this);if(c.bookName.html()||c.bookDes.html()){c.point.show();c.description.show()}});h.bind("mouseover",
function(){c.overObj=$(this);$(this).stop(false,true).animate({opacity:1},500);c.setDescriptionPosition(b,a,this);if(c.bookName.html()||c.bookDes.html()){c.point.show();c.description.show()}})})(g);g!=b.length-1&&$("<div>",{css:{position:"relative",display:"block",width:"100%",padding:"11px 0px"}}).appendTo(a)}this.createScrollBar(this.bookView,this.booksList)},bindEvents:function(){var a=this;$(document).bind("click",function(){a.title.removeClass("active")});this.innerTitle.bind("click",function(b){a.title.toggleClass("active");
b.stopPropagation()});this.showHide.bind("click",function(){a.issuesShow?a.hide():a.show()})},createScrollBar:function(a,b){var d=a.outerHeight(),c=b.width(),e=d/b.outerHeight(),e=d*(1<e?1:e),d=$("<div>",{"class":"ScrollBar",css:{position:"absolute",width:4,height:d,backgroundColor:"#d5d5d5",borderRadius:0,marginLeft:(this.bookViewLeft-4)/2,left:c,top:0}}).appendTo(a),c=$("<div>",{"class":"OuterScroll",css:{position:"absolute",width:4,height:e,left:0,top:0,backgroundColor:"transparent",borderRadius:0,
overflow:"hidden",cursor:"pointer"}}).appendTo(d);$("<div>",{"class":"InnerScroll",css:{position:"absolute",width:4,height:"100%",marginLeft:0,marginRight:0,left:0,top:0,backgroundColor:"#929292",borderRadius:0,cursor:"pointer"}}).appendTo(c);a.outerHeight()>=b.outerHeight()&&d.hide();this.scrollBar=d;this.outerScroll=c;this.bindScrollBarEvents(d,c,a,b)},bindScrollBarEvents:function(a,b,d,c){var e=this;b.bind("mousedown",function(a){var d=a||event,h=d.clientY-e.outerScroll.position().top,i=a.which;
a.stopPropagation();1==i&&($(document).bind("mousemove",function(a){a.preventDefault();a.stopPropagation();d=a||event;a=d.clientY-h;0>=a?a=0:a>=e.scrollBar.outerHeight()-e.outerScroll.outerHeight()&&(a=e.scrollBar.outerHeight()-e.outerScroll.outerHeight());b.css({top:a});c.css({top:-a/(e.scrollBar.outerHeight()-e.outerScroll.outerHeight())*(e.booksList.outerHeight()-e.bookView.outerHeight())});e.setDescriptionPosition2()}).bind("mouseup",function(a){a=a||event;a.preventDefault();$(document).unbind("mousemove");
a.stopPropagation()}),$(document).bind("mouseup",function(a){a=a||event;a.preventDefault();a.stopPropagation();$(document).unbind("mousemove")}))});d.bind($.browser.mozilla?"DOMMouseScroll":"mousewheel",function(f){if(!(d.outerHeight()>=c.outerHeight())){var f=f.originalEvent,f=f.wheelDelta||-f.detail,g=c.position().top,h;c.stop(!1,!1);0<f?h=0>g+d.outerHeight()/11?g+d.outerHeight()/11:0:0>f&&(h=c.outerHeight()-d.outerHeight()>-(g-d.outerHeight()/11)?g-d.outerHeight()/11:-(c.outerHeight()-d.outerHeight()));
c.css({top:h});b.css({top:-h/(c.outerHeight()-d.outerHeight())*(a.outerHeight()-b.outerHeight())});e.setDescriptionPosition2()}})},calculateScrollBar:function(){var a=this.bookView.outerHeight()*this.scrollBar.outerHeight()/this.booksList.outerHeight();this.bookView.outerHeight()>=this.booksList.outerHeight()?(this.scrollBar.hide(),this.booksList.css({top:0})):this.scrollBar.show();this.outerScroll.css({height:a})},setDescriptionPosition:function(a,b,d){var c=$(d).offset().top-4-this.outBookView.offset().top,
e=Math.min($(d).offset().top-4-this.outBookView.offset().top+$(d).outerHeight(),this.bookView.outerHeight()-($(d).offset().top-4-this.outBookView.offset().top),this.bookView.outerHeight(),$(d).outerHeight());this.bookName.html(a[b].name);this.bookDes.html(a[b].description);a[b].name&&a[b].description&&this.bookName.css({paddingBottom:"0.6em"});e=Math.min($(d).offset().top-4-this.outBookView.offset().top+$(d).outerHeight(),this.bookView.outerHeight()-($(d).offset().top-4-this.outBookView.offset().top),
this.bookView.outerHeight(),$(d).outerHeight());a=-(this.titleHeight+this.titleTop+this.bookBottom+this.issuesTop);this.description.css({top:Math.min(Math.max(0<c?c+(e-this.description.outerHeight())/2:(e-this.description.outerHeight())/2,a),this.father.outerHeight()-this.description.outerHeight()+a)});this.point.css({top:0<c?c+(e-this.point.outerHeight())/2:(e-this.point.outerHeight())/2})},setDescriptionPosition2:function(){if(this.overObj){var a=this.overObj.offset().top-4-this.outBookView.offset().top,
b=Math.min(this.overObj.offset().top-4-this.outBookView.offset().top+this.overObj.outerHeight(),this.bookView.outerHeight()-(this.overObj.offset().top-4-this.outBookView.offset().top),this.bookView.outerHeight(),this.overObj.outerHeight()),d=-(this.titleHeight+this.titleTop+this.bookBottom+this.issuesTop);this.description.css({top:Math.min(Math.max(0<a?a+(b-this.description.outerHeight())/2:(b-this.description.outerHeight())/2,d),this.father.outerHeight()-this.description.outerHeight()+d)});this.point.css({top:0<
a?a+(b-this.point.outerHeight())/2:(b-this.point.outerHeight())/2})}},resize:function(a){this.issuesHeight=a.height()-this.issuesTop-this.issuesBottom;this.outIssues.css({height:this.issuesHeight});this.lBoxShow.css({height:this.issuesHeight-1});this.bBoxShow.css({height:this.issuesHeight-2});this.bookViewHeight=this.issuesHeight-this.bookViewTop-this.bookBottom;this.outBookView.css({height:this.bookViewHeight});this.scrollBar.css({height:this.bookViewHeight});this.bookViewHeight-this.booksList.outerHeight()>=
parseInt(this.booksList.css("top"))&&this.booksList.outerHeight()>this.bookViewHeight&&this.booksList.css({top:this.bookViewHeight-this.booksList.outerHeight()});this.outerScroll.css({top:-parseInt(this.booksList.css("top"))/(this.booksList.outerHeight()-this.outBookView.outerHeight())*(this.scrollBar.outerHeight()-this.outerScroll.outerHeight())});this.calculateScrollBar()},destroy:function(){this.outIssues.remove()}};
function ajaxLink(a,b,d){var c=window.location.pathname.split("/");$.ajax({type:"get",url:"http://fliphtml5.com/hostInfo/get-all-books-by-book.php",dataType:"jsonp",data:{ulink:c[1],blink:c[2]},success:function(c){d.backIssues=new BackIssues(c,a,b)},error:function(){console.log("error")}})}
(function(a){var b=a(document);b.backIssues=null;a(document).bind(fullScreenApi.fullScreenEventName,function(){fullScreenApi.isFullScreen()?b.backIssues?b.backIssues&&b.backIssues.setHide().outIssues.show():ajaxLink(a("#tmpContainer"),uiBaseURL,b):b.backIssues&&b.backIssues.outIssues.hide()})})(jQuery);
